#!/usr/bin/env ruby

remote = %x(git remote get-url origin)
if remote.start_with? 'git@'
	remote = remote.gsub(':', '/').gsub('git@', 'http://').chomp.chomp(".git")
end

if remote.include? 'bitbucket'
	remote = remote.concat('/branch')
else
	remote = remote.concat('/tree/')
end

branches = %x(git branch).split(' ')
current_branch = ''
branches.each_with_index do |branch, index|
	current_branch =  branches[index + 1] if branch.include?('*')
end
puts current_branch
remote = "#{remote}#{current_branch}"
puts remote	
%x(open #{remote})
